FIND_PATH(TRIMESH2_DIR	include/TriMesh.h
  MESSAGE("*** TRIMESH2_DIR = ${TRIMESH2_DIR}")
  HINTS ENV TRIMESH2_DIR
  PATHS
  DOC	"The trimesh2 directory"
)

SET(TRIMESH2_ARCH $ENV{TRIMESH2_ARCH})
SET(TRIMESH2_INCLUDE_DIR "${TRIMESH2_DIR}/include")
SET(TRIMESH2_LIB_DIR     "${TRIMESH2_DIR}/lib.${TRIMESH2_ARCH}" )

FIND_LIBRARY(TRIMESH2_LIB     trimesh
             HINTS ${TRIMESH2_LIB_DIR})
FIND_LIBRARY(GLUIT_LIB     gluit
             HINTS ${TRIMESH2_LIB_DIR})
SET(TRIMESH2_LIBRARIES ${TRIMESH2_LIB} ${GLUIT_LIB} CACHE STRING "trimesh2 libraries" FORCE)

# handle the QUIETLY and REQUIRED arguments and set ALSA_FOUND to TRUE if 
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Trimesh2 DEFAULT_MSG TRIMESH2_LIBRARIES TRIMESH2_INCLUDE_DIR TRIMESH2_DIR)

IF ( TRIMESH2_FOUND )
  SET( TRIMESH2_INCLUDES ${TRIMESH2_INCLUDE_DIR} CACHE STRING "trimesh2 include path" FORCE)
ENDIF()

MARK_AS_ADVANCED(TRIMESH2_LIBRARIES TRIMESH2_INCLUDES)
