FIND_PATH(TRIMESH2_DIR	include/TriMesh.h
  MESSAGE("*** TRIMESH2_DIR = ${TRIMESH2_DIR}")
  HINTS ENV TRIMESH2_DIR
  PATHS
  DOC	"The trimesh2 directory"
)

SET(TRIMESH2_ARCH $ENV{TRIMESH2_ARCH})
SET(TRIMESH2_INCLUDE_DIR "${TRIMESH2_DIR}/include")
SET(TRIMESH2_LIB_DIR     "${TRIMESH2_DIR}/lib.${TRIMESH2_ARCH}" )

FIND_LIBRARY(TRIMESH2_LIB     trimesh
             HINTS ${TRIMESH2_LIB_DIR})
SET(TRIMESH2_LIBRARIES ${TRIMESH2_LIB} CACHE STRING "trimesh2 libraries" FORCE)

IF ( TRIMESH2_DIR AND TRIMESH2_LIBRARIES )
  SET(HAVE_TRIMESH2 1)
  SET(TRIMESH2_FOUND ON)
  MESSAGE( "-- Found Trimesh2: ${TRIMESH2_LIBRARIES}" )
  SET( TRIMESH2_INCLUDES ${TRIMESH2_INCLUDE_DIR} CACHE STRING "trimesh2 include path" FORCE)
ENDIF()

MARK_AS_ADVANCED(TRIMESH2_LIBRARIES TRIMESH2_INCLUDES)
